### ISSUE TITLE
Month offset by +1

### ISSUE THREAD

**Issue by johnhorsema** [pastelsky/covid-19-mobility-tracker#2]
Comparing the actual PDF chart with the API, the month unit is offset by +1.
e.g. Latest available figure is dated March 29, but the API returns "2020-04-29" in the most recent datapoint

The correct offset should be 0.

**Comment by pastelsky** [comment]
Good catch! Will refresh this in a bit.

**Comment by pastelsky** [comment]
@johnhorsema This should be fixed now.
