### ISSUE TITLE
Missing country outputs

### ISSUE THREAD

**Issue by crmnz** [pastelsky/covid-19-mobility-tracker#6]
Mobility reports of the Bahamas, Guinea-Bissau, South Korea, Liechtenstein and Réunion are missing in the output folder (ISO2 codes BS, GW, KR, LI, RE).

**Comment by pastelsky** [comment]
Good catch. Added data for Korea and Bahamas. For the rest – some graphs have missing data (due to statistical significance) and that's something the current logic cannot process reliably.
