### ISSUE TITLE
US County Level Data

### ISSUE THREAD

**Issue by jqnatividad** [pastelsky/covid-19-mobility-tracker#9]
First off, thanks for this valuable resource!

Do you have any plans to parse the county-level info as well for the US?

The aggregate data on a State basis is not really as actionable...

Thanks again!

**Comment by arjunnambiartc** [comment]
Google now publishes a CSV along with the PDF which has all the necessary including county-level data..https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv

**Comment by pastelsky** [comment]
Parsing County level data is a lot of work, and I'd recommend you use the official CSVs for that. Thanks.
